### ISSUE TITLE
error when creating installer..

### ISSUE THREAD

**Issue by henrykey** [Qquanwei/electron-windows-inno-installer#4]
I get error when use it.
usage:electron-windows-inno-installer example.iss --icon ./img/icons/IconTemplate --platform win32-x64
OS: Mac OSX
and it's ok to pack them with electron-packager and err msg as follows:
[20:59:52] Using gulpfile /usr/local/lib/node_modules/electron-windows-inno-installer/gulpfile.js
[20:59:52] Starting 'version'...
[20:59:52] Finished 'version' after 1.22 ms
[20:59:52] Starting 'copy:modules'...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: EISDIR: illegal operation on a directory, read

thx

**Comment by Qquanwei** [comment]
Are you have a directory named `package.json` ?

execute 
```
find . -name "package.json" -type d    
```
have match direction?

**Comment by henrykey** [comment]
no, I don't.

**Comment by henrykey** [comment]
it's done. thx

**Comment by henrykey** [comment]
the installer has created successfully after I clean up extra content in node_module. the app installed using the installer doesn't work. I don't know why. it seems the entry point not correct.
All my source file is in dir of src, is this a problem to use the tool?
project tree is like this 
/--src--components
      |---main.js
      |---main.html
   ...
    node_modules
    img--icons
      |--- logo.png
    package.json
    example.iss
...

is this a problem?

**Comment by Qquanwei** [comment]
It's my problem , fix by later :)

ths

**Comment by henrykey** [comment]
it's ok now. I put   "sourceFiles":[ "./src/**/**",    "./img/**/**", "./vendor/**/**"]" into package.json.
thx

**Comment by jokyme** [comment]
I encountered the same problem
