### ISSUE TITLE
iss file source file does not exist

### ISSUE THREAD

**Issue by mail2chensh** [Qquanwei/electron-windows-inno-installer#6]
when I build the project like:

> electron-windows-inno-installer ./example.iss --platform win32-x64 --icon ./login.ico

there have a error : 

> stderr: Error on line 41 in Z:\Users\chensh\Desktop\longyuan\example.iss: Source file "Z:\Users\chensh\Desktop\longyuan\release/v1.4.3/win32-ia32/example.exe" does not exist.

how can I resolve this problem?

**Comment by Qquanwei** [comment]
```
vim example.iss
```
and replace '/path/to/example.exe' to '/path/to/your.exe'
