### ISSUE TITLE
安装后的程序，无法创建桌面图标

### ISSUE THREAD

**Issue by xiaochen2012** [Qquanwei/electron-windows-inno-installer#9]
![image](https://user-images.githubusercontent.com/3153927/26859484-985ed4b8-4b6a-11e7-87fa-329e08acdba0.png)
在哪里可以设置。

**Comment by Qquanwei** [comment]
这个可能是inno-setup本身的一个bug，我在win7 与 win10系统上测试过是正常的，所以我也不太清楚这个情况，很抱歉无法帮到你。

**Comment by xiaochen2012** [comment]
0
